HTTP/1.0 200 OK
Content-Type: text/html; charset=UTF-8
Connection: close

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Calendar</title>
    <style>
        body {
            margin: 0;
            padding: 0;

            font-family: sans-serif;
        }

        section {
            width: 100vw;
            height: 100vh;
            page-break-after: always;

            display: flex;
            flex-flow: column nowrap;

            border-style: solid solid;
        }

        header {
            display: flex;
            flex-flow: row nowrap;
        }

        header>* {
            flex: 1;
        }

        main {
            flex: 1;

            display: grid;
            grid-template-columns: 1fr 1fr 1fr 1fr 1fr 1fr 1fr;
        }

        .cell {
            display: flex;
            flex-flow: column nowrap;
        }

        section,
        .cell {
            border-width: 1pt;
            border-color: black;
        }

        header {
            text-align: center;
        }

        .cell:nth-child(-n+7) {
            border-top-style: solid;
        }

        .cell:not(:nth-child(7n+1)) {
            border-left-style: solid;
        }

        .cell:nth-child(-n+28) {
            border-bottom-style: solid;
        }

        .shadedBackground,
        .cell:nth-child(7n),
        .cell:nth-child(7n-1) {
            background-color: rgb(255, 255, 153);
        }

        .event {
            color: red;
        }

        .month_and_year {
            grid-column: 6 / span 2;

            font-size: 2em;
            text-align: center;

            display: flex;
            flex-flow: column nowrap;
            justify-content: center;
            align-items: center;
        }
    </style>
</head>

<body>
    {% for month_events in events %}
    <section>
        <header>
            <span>Monday</span>
            <span>Tuesday</span>
            <span>Wednesday</span>
            <span>Thursday</span>
            <span>Friday</span>
            <span class="shadedBackground">Saturday</span>
            <span class="shadedBackground">Sunday</span>
        </header>
        <main>
            {% for day in month_events %}
            {% match day %}
            {% when CalendarCell::Empty %}
            <span class="cell"></span>
            {% when CalendarCell::Day with {day, events} %}
            <span class="cell">
                <span>{{day}}</span>
                {% for event in events %}
                <span class="event">{{event}}</span>
                {% endfor %}
            </span>
            {% when CalendarCell::MonthAndYear with {month, year} %}
            <span class="cell month_and_year"><span>{{month.name()}} {{year}}</span></span>
            {% endmatch %}
        {% endfor %}
        </main>
    </section>
    {% endfor %}
</body>

</html>